name="Rudrashis Kumar Dutta";
roll=1906354;
email="rudra2001official@gmail.com";
addressLine1="Bajrakabati Road";
addressLine2="Cuttack - 753001";
echo "Student Name:\t"$name;
echo "Roll Number:\t"$roll;
echo "Email:\t"$email;
echo "Address 1st Line:\t"$addressLine1;
echo "Address 2nd Line:\t"$addressLine2;
